---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dockerhub-mirror-registry
  namespace: registry
spec:
  secretName: dockerhub-mirror-crt
  renewBefore: 12h
  dnsNames:
   #- set your valid domain
    - registry.docker.com
  issuerRef:
  # change name with your k8s cluster-issuer
   name: letsencrypt
   kind: ClusterIssuer
---
apiVersion: v1
kind: Service
metadata:
  name: docker-app-service
  namespace: registry
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    environment: production
    app: docker-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: production
    app: docker-app
  name: docker-app-deployment
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: production
      app: docker-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        environment: production
        app: docker-app
    spec:
      containers:
      - image: registry:latest
        imagePullPolicy: IfNotPresent
        name: docker-app-deployment-pod
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: registry-configmap
          items:
          - key: config.yml
            path: config.yml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dockerhub-mirror-registry
  namespace: registry
spec:
  entryPoints:
    - web
    - websecure
  routes:
    #- set your valid domain
    - match: Host(`registry.docker.com`)
      kind: Rule
      services:
        - name: docker-app-service
          port: 5000
  tls:
    secretName: dockerhub-mirror-crt